# .github/workflows/qa.yml
name: Deploy to Cloud Run QA
on:
  push:
    branches:
      - qa
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: test
  RUN_REGION: us-central1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    #if: "contains(github.event.head_commit.message, 'new version')"
    steps:
      - uses: actions/checkout@v2
      
      # Setup gcloud CLI
     # - uses: GoogleCloudPlatform/github-actions/setup-glcoud@v0
      #check
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Export gcloud related env variable
        run: export CLOUDSDK_PYTHON="/usr/bin/python3"
      - uses: google-github-actions/setup-gcloud@v0
        with: 
          version: "318.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      - name: Deploy
        run: gcloud run deploy $APP_ID --image gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated
